--- 
  - name: Enabling Patching in AWS 
    hosts: localhost
    connection: local
    gather_facts: no
    sudo: yes
    vars_files:
    - [var.yml]
    tasks: 
        - name: Creating IAM Role named 'EC2-Systems-Manager-Role' and Attaching Policy.
          command: aws iam create-role --role-name EC2-Systems-Manager-Role --assume-role-policy-document file://trust_policy.json

        - name: Creating IAM instance profile.
          command: aws iam create-instance-profile --instance-profile-name EC2-Systems-Manager-Profile

        - name: Adding role to IAM instance profile.
          command: aws iam add-role-to-instance-profile --instance-profile-name EC2-Systems-Manager-Profile --role-name EC2-Systems-Manager-Role

        - name: Pausing playbook execution for role to get added into instance profile.
          pause:
            seconds: 30 

        - name: Adding Iam Instance profile ec2 instance
          command: aws ec2 associate-iam-instance-profile --instance-id i-0ce2fc1242b26ce20 --iam-instance-profile Name="EC2-Systems-Manager-Profile"
          register: aid
        - local_action: copy content={{ aid.stdout }} dest=/home/automation/ajishaws/ansibleaws_files/neha/association.yml

        - name: Adding Tag to ec2 instance.
          command: aws ec2 create-tags --resources i-0ce2fc1242b26ce20 --tags Key='Patch Group',Value='Test-Patch'

        - name: Creating User ssmPatchUser
          command: aws iam create-user --user-name ssmPatchUser

        - name: Creating policy
          command: aws iam create-policy --policy-name ssmPassRole --policy-document file://ssmpassrole.json

        - name: Attaching policy to user
          command: aws iam attach-user-policy --policy-arn arn:aws:iam::854007681527:policy/ssmPassRole --user-name ssmPatchUser

        - name: Attaching policy to user
          command: aws iam attach-user-policy --policy-arn arn:aws:iam::aws:policy/AmazonSSMFullAccess --user-name ssmPatchUser

        - name: Creating Patch Baseline
          command: aws ssm create-patch-baseline --name "testBaseline1" --approval-rules "PatchRules=[{PatchFilterGroup={PatchFilters=[{Key=MSRC_SEVERITY,Values=[Critical,Important,Moderate]},{Key=CLASSIFICATION,Values=[SecurityUpdates,Updates,UpdateRollups,CriticalUpdates]}]},ApproveAfterDays=1}]" --description "myBaseline"
          register: baselineid
        - local_action: copy content={{ baselineid.stdout }} dest=/home/automation/ajishaws/ansibleaws_files/neha/baselineid.yml
        - name: Pausing for 30 seconds.
          pause:
            seconds: 30
        - name: Including Baseline id.
          include_vars:
                 file: /home/automation/ajishaws/ansibleaws_files/neha/baselineid.yml
                 name: baseid

        - name: Linking PatchBaseline With
          command: aws ssm register-patch-baseline-for-patch-group --baseline-id {{ baseid.BaselineId }} --patch-group "Test-Patch"

        - name: Creating Maintenance Window
          command: aws ssm create-maintenance-window --name myFirstMaintenanceWindow1 --schedule "cron(0 00 15 ? * MON-FRI)" --duration 6 --cutoff 1 --allow-unassociated-targets
          register: winid
        - local_action: copy content={{ winid.stdout }} dest=/home/automation/ajishaws/ansibleaws_files/neha/winid.yml
        - name: pausing for 30 seconds.
          pause:
            seconds: 30
        - name: Including Window Id.
          include_vars:
                 file: /home/automation/ajishaws/ansibleaws_files/neha/winid.yml
                 name: wid

        - name: Registering target with maintenace window
          command: aws ssm register-target-with-maintenance-window --window-id {{ wid.WindowId }} --targets "Key=tag:Patch Group,Values=Test-Patch" --owner-information "Test server" --resource-type "INSTANCE"
          register: wintargetid
        - local_action: copy content={{ wintargetid.stdout }} dest=/home/automation/ajishaws/ansibleaws_files/neha/wintargetid.yml
        - name: pausing for 20 seconds.
          pause:
            seconds: 20
        - name: Including Window Target Id.
          include_vars:
                 file: /home/automation/ajishaws/ansibleaws_files/neha/wintargetid.yml
                 name: wtid

        - name: Registering task with maintenance window
          command: aws ssm register-task-with-maintenance-window --window-id {{ wid.WindowId }} --targets "Key=WindowTargetIds,Values={{ wtid.WindowTargetId }}" --task-arn "AWS-ApplyPatchBaseline" --service-role-arn "arn:aws:iam::854007681527:policy/ssmPassRole" --task-type "RUN_COMMAND" --max-concurrency 2 --max-errors 1 --priority 1 --task-parameters "{\"Operation\":{\"Values\":[\"Install\"]}}"
          register: wintaskid
        - local_action: copy content={{ wintaskid.stdout }} dest=/home/automation/ajishaws/ansibleaws_files/neha/wintaskid.yml

          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
