---
 -  hosts: localhost
    connection: local
    vars_files:
    - [var.yml]
    tasks:
    - name: Deleting User Neha
      iam:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        iam_type: user
        name: Neha
        state: absent
